language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm: 2.2.2
sudo: false
services:
  - memcached
branches:
  only: [master]
env:
  matrix:
    - DB=mysql TASK=rake
    - DB=mysql TASK=js
    - DB=mysql TASK=precompile
    - DB=postgresql TASK=rake
    - DB=postgresql TASK=js
    - DB=postgresql TASK=precompile
    - DB=sqlite TASK=rake
    - DB=sqlite TASK=js
    - DB=sqlite TASK=precompile
script: script/ci.rb
