language: ruby
cache:
  bundler: true
  directories:
    - node_modules
rvm: 2.2.2
sudo: false
services:
  - memcached
branches:
  only: [master]
env:
  matrix:
    - TASK=js
    - TASK=precompile
    - DATABASE_URL=mysql2://travis@127.0.0.1/samson_test TASK=rake
    - DATABASE_URL=postgresql://postgres@127.0.0.1/samson_test TASK=rake
    - DATABASE_URL=sqlite3://null$PWD/db/test.sqlite3 TASK=rake
script: script/ci
