version: "2"
services:
  samson:
    image: zendesk/samson:latest
    ports:
      - "9080:9080"
    environment:
      DATABASE_URL: "sqlite3://db/development.sqlite"
      RAILS_LOG_TO_STDOUT: 1
    command: ["bash", "-c", "./bin/decode_dot_env .env.compose && source <(sed -E -n 's/[^#]+/export &/ p' .env.compose) && rake db:setup && bundle exec puma -C config/puma.rb"]
