sqlite: &sqlite
  adapter: sqlite3
  database: db/test.sqlite3

mysql: &mysql
  adapter: mysql2
  username: travis
  encoding: utf8mb4
  collation: utf8mb4_bin

postgresql: &postgresql
  adapter: postgresql
  username: postgres

test: &test
  database: samson_test
  pool: 5
  encoding: utf8
  <<: *<%= ENV['DB'] || "sqlite" %>

# for asset compilation test
production:
  <<: *test
